### ISSUE TITLE
Add .position() mixin

### ISSUE THREAD

**Issue by mdo** [mdo/preboot#28]
For example:

``` css
/* Mixin */
.position(@position, @top, @right, @bottom, @left) {
  position: @position;
  top: @top;
  right: @right;
  bottom: @bottom;
  left: @left;
}

/* Usage */
.element {
  .position(absolute, 0, 20px, auto, auto);
}
```

**Comment by KittyGiraudel** [comment]
Was about to suggest it. Demo here: http://codepen.io/HugoGiraudel/pen/2f281e61e1dab99710f008f1f6eb954c.

Added the position (default absolute) as a last parameter to ommit it most of the time.

**Comment by tamaspap** [comment]
Exactly what I wanted to suggest!

**Comment by boulox** [comment]
A point down for the use of this mixin would be to create extra line of css. When use positioning in css it's not that often we need to define all the 4 top/right/bottom/left.

Still an interesting mixin +1 to add it to the lib

**Comment by mdo** [comment]
If we can prevent unused properties from being included, that'd be awesome. Otherwise I don't think I'll add this. Any thoughts?

**Comment by boulox** [comment]
Since less don't provide the use of if conditionals to handle the empty-string case, it would need some not so pretty hack to do it.

Here is my way to do it (there is definitely some other work around ?) :

``` CSS
/* Mixin */
.position-top(@top) when (@top = null) { }
.position-top(@top) when not (@top = null) {
  top: @top;
}

.position-right(@right) when (@right = null) { }
.position-right(@right) when not (@right = null) {
  right: @right;
}

.position-bottom(@bottom) when (@bottom = null) { }
.position-bottom(@bottom) when not (@bottom = null) {
  bottom: @bottom;
}

.position-left(@left) when (@left = null) { }
.position-left(@left) when not (@left = null) {
  left: @left;
}

.position(@position, @top, @right, @bottom, @left) {
  position: @position;
  .position-top(@top);
  .position-right(@right);
  .position-bottom(@bottom);
  .position-left(@left);
}

/* Usage */
.element {
  .position(absolute, 0, 20px, null, auto);
}
```

**Comment by maniqui** [comment]
Half-inspired by @boulox's mixin, half-inspired by [this answer at SO](http://stackoverflow.com/a/15512461), I came up with this .position() mixin: 

```
.position(@position:absolute, @top:null, @right:null, @bottom:null, @left:null) {
  position: @position;
  .property(top, @top);
  .property(right, @right);
  .property(bottom, @bottom);
  .property(left, @left);

  .property(@property, @value) {

    // "Private" method
    ._getProp(top) when not (@top = null) {
      top: @value;
    }

    ._getProp(right) when not (@right = null) {
      right: @value;
    }

    ._getProp(bottom) when not (@bottom = null) {
      bottom: @value;
    }

    ._getProp(left) when not (@left = null) {
      left: @value;
    }

    ._getProp(@property);    

  };

}

// Usage

.element {
  .position(@left:10px, @bottom:0);
}

.element {
  .position(relative, @right:10px, @top:20px);
}

.element {
  .position(@right:10px, @bottom:30px, @position:relative);
}

.element {
  .position(absolute, 0, 20px, null, null);
}

// Alternative usage (probably unneeded)
.element {
  @bottom: 10px;
  .position .property(bottom, @bottom);
}
```

Some things to observe:
- doesn't include (iin output) unused properties.
- has sensible defaults (imo).
- can be called with keyword arguments (a.k.a. named arguments), which makes it more readable & easier to use.
- keeps some stuff namespaced and names a method in a way that seems to indicate it's private (`._someMethod()`)

@mdo: what do you think?

**Comment by maniqui** [comment]
This is slight variation from the above one, which also use the `._getProp()` method to include the `position` property.
Useful (to avoid code duplication) in the case the element already has a `position` property declared somewhere else (ie. on a previous matching rule on the cascade, or somewhere outside the mixin). 
Feel free to test it in http://less2css.org

```
.position(@position: null, @top: null, @right: null, @bottom: null, @left: null) {
  .property(position, @position);
  .property(top, @top);
  .property(right, @right);
  .property(bottom, @bottom);
  .property(left, @left);

  .property(@property, @value) {

    ._getProp(position) when not (@position = null) {
      position: @value;
    }

    ._getProp(top) when not (@top = null) {
      top: @value;
    }

    ._getProp(right) when not (@right = null) {
      right: @value;
    }

    ._getProp(bottom) when not (@bottom = null) {
      bottom: @value;
    }

    ._getProp(left) when not (@left = null) {
      left: @value;
    }

    ._getProp(@property);    

  };

}

// Usage

.element {
  .position(@left:10px, @bottom:0);
}

.element {
  .position(relative, @right:10px, @top:20px);
}

.element {
  .position(@right:10px, @bottom:30px, @position:relative);
}

.element {
  .position(absolute, 0, 20px, null, null);
}

// Alternative usage (probably unneeded)
.element {
  @bottom: 10px;
  .position .property(bottom, @bottom);
}
```

_Edit_: edit on default value for `position` parameter, making it `null`.

**Comment by maniqui** [comment]
It may be useful to include a `@z-index` parameter too.

**Comment by mdo** [comment]
Punting on this.

**Comment by gfellerph** [comment]
What do you think of this?

``` less
.position (@top, @right: @top, @bottom: @top, @left: @right, @position: absolute) {
    position: @position;
    top: @top;
    right: @right;
    bottom: @bottom;
    left: @left;
}

/* Use similar to CSS shorthands */
.position(20px, @position: fixed);
.position(auto, 20px);
.position(10px, 2em, 5%);
.position(1px, 2px, 3px, 4px);
```
