### ISSUE TITLE
.size() improvement to replace .square()

### ISSUE THREAD

**Issue by KittyGiraudel** [mdo/preboot#30]
You currently use 2 mixins for sizing: `.size(@w, @h)` and `.square(@w)`. Maybe you could use a single one, making the whole thing easier to use.

I'm definitely not a LESS ninja, but here is what I came with. Probably could it be improved:

```
.size(@width, @height) {
  width: @width;
  height: @height; 
}

.size(@width, @height: 0) when (@height = 0) {
  width: @width;
  height: @width; 
}

.a {
  .size(10em);
} 
```

http://codepen.io/HugoGiraudel/pen/db3e3a09a9f0ad9e477da50f6d394f46

**Comment by tamaspap** [comment]
But in some cases you actually want height = 0.

**Comment by KittyGiraudel** [comment]
Then use `none` instead of `0`. It works as well.

```
.size(@width, @height) {
  width: @width;
  height: @height; 
}

.size(@width, @height: none) when (@height = none) {
  width: @width;
  height: @width; 
}

.a {
  .size(10em);
} 
```

**Comment by boulox** [comment]
the simplest way to do it :

``` CSS
/* Mixin */
.size(@square) {
  width: @square;
  height: @square;
}

.size(@width, @height) {
  width: @width;
  height: @height;
}

/* Usage */
.element {
   .size(10px); // render width:10px; height:10px;
}

.element {
   .size(10px, 20px); // render width:10px; height: 20px;
}
```
