### ISSUE TITLE
Generic .transform() mixin is missing

### ISSUE THREAD

**Issue by iSimonWeb** [mdo/preboot#35]
If I want to apply multiple transformation on a singler rule?
I think is missing a mixin like this:

``` css
.transform(@transformations) {
  -webkit-transform: @transformations;
     -moz-transform: @transformations;
      -ms-transform: @transformations;
       -o-transform: @transformations;
          transform: @transformations;
}
```
